"""Tests for the optional FastAPI portal (the PLAN path only).

Fully offline: uses fastapi.testclient.TestClient and the mock LLM backend,
no network and no real API key needed. Skips cleanly when the test client
isn't available (the `portal` extra is optional).

Guarded on TestClient itself rather than on `fastapi`, and catching
RuntimeError as well as ImportError: fastapi can import perfectly while
`fastapi.testclient` still fails, because starlette raises RuntimeError —
not ImportError — when its HTTP client dependency is missing. A plain
`importorskip("fastapi")` lets that through as a hard collection error.
"""

import json
import threading
import time
from pathlib import Path

import pytest

try:
    from fastapi.testclient import TestClient
except (ImportError, RuntimeError) as exc:
    pytest.skip(f"fastapi TestClient unavailable: {exc}", allow_module_level=True)

import moviecrew.mock as mock_module  # noqa: E402
from moviecrew.portal.app import _sessions, app  # noqa: E402

client = TestClient(app)


def _wait_for_plan(session_id: str, timeout: float = 5.0) -> dict:
    """Poll GET .../plan until generation finishes, returning the final body.

    Stands in for the browser's ~1s polling loop. With the mock LLM and no
    gate blocking anything, generation finishes in well under a second, so
    a short poll interval is enough — this never sleeps anywhere near
    *timeout* on the happy path.
    """
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        body = client.get(f"/api/session/{session_id}/plan").json()
        if body["status"] in ("complete", "failed"):
            return body
        time.sleep(0.01)
    raise AssertionError(f"plan for session {session_id!r} did not finish within {timeout}s")


class _Gate:
    """Lets a test pause the background plan-generation thread just before
    a chosen pipeline task's mock LLM call, so progress state can be
    inspected deterministically — without this, the mock LLM is fast enough
    that a background job can finish before a test ever gets to look at it
    mid-flight.
    """

    def __init__(self, calls, task_holder, reached, release):
        self.calls = calls
        self._task_holder = task_holder
        self._reached = reached
        self._release = release

    def block_before(self, task: str) -> None:
        self._task_holder["value"] = task

    def wait_until_reached(self, timeout: float = 5.0) -> None:
        assert self._reached.wait(timeout), (
            f"task {self._task_holder['value']!r} was never reached within {timeout}s"
        )
        self._reached.clear()

    def step(self, timeout: float = 5.0) -> bool:
        """Release the currently blocked call and wait for the *next* call
        to the gated task to arrive. Returns False (instead of hanging)
        if generation finished without one — e.g. stepping past the last
        shot's prompter call.
        """
        self._reached.clear()
        self._release.set()
        got = self._reached.wait(timeout)
        if got:
            self._reached.clear()
        return got

    def stop_blocking(self) -> None:
        """Stop gating further calls and release whatever is blocked now."""
        self._task_holder["value"] = None
        self._release.set()


@pytest.fixture
def gate(monkeypatch):
    calls: list[str] = []
    task_holder = {"value": None}
    reached = threading.Event()
    release = threading.Event()
    original = mock_module.MockLLMClient.complete_json

    def gated(self, *, task, system, user):
        calls.append(task)
        if task == task_holder["value"]:
            reached.set()
            release.wait(timeout=5)
            release.clear()
        return original(self, task=task, system=system, user=user)

    monkeypatch.setattr(mock_module.MockLLMClient, "complete_json", gated)
    return _Gate(calls, task_holder, reached, release)


@pytest.fixture
def call_log(monkeypatch):
    """Record every `task` passed to the mock LLM's complete_json, in the
    order it was invoked, without altering its behavior. Used to prove what
    did and did not get (re)generated by a given request.
    """
    calls: list[str] = []
    original = mock_module.MockLLMClient.complete_json

    def recording(self, *, task, system, user):
        calls.append(task)
        return original(self, task=task, system=system, user=user)

    monkeypatch.setattr(mock_module.MockLLMClient, "complete_json", recording)
    return calls


@pytest.fixture
def failing_continuity(monkeypatch):
    """Simulate the reported failure: continuity fails after everything
    else generated successfully. Patches the mock backend's own class
    method so the real code path (crew.make() / the continuity endpoint,
    through the mock LLM) is exercised, not a stand-in for it. Also records
    every task invoked, like call_log, so callers can assert on exactly
    what ran.
    """
    calls: list[str] = []
    original = mock_module.MockLLMClient.complete_json

    def sometimes_failing(self, *, task, system, user):
        calls.append(task)
        if task == "continuity":
            raise RuntimeError("simulated continuity outage")
        return original(self, task=task, system=system, user=user)

    monkeypatch.setattr(mock_module.MockLLMClient, "complete_json", sometimes_failing)
    return calls


@pytest.fixture
def failing_editor(monkeypatch):
    """Simulate plan generation itself failing partway through, after the
    (single, in the mock) scene's shots have already landed."""
    original = mock_module.MockLLMClient.complete_json

    def sometimes_failing(self, *, task, system, user):
        if task == "editor":
            raise RuntimeError("simulated editor outage")
        return original(self, task=task, system=system, user=user)

    monkeypatch.setattr(mock_module.MockLLMClient, "complete_json", sometimes_failing)


def test_health_lists_backends_and_detail_levels():
    res = client.get("/api/health")
    assert res.status_code == 200
    data = res.json()
    assert data["ok"] is True
    assert "mock" in data["backends"]
    assert "anthropic" in data["backends"]
    assert set(data["detail_levels"]) == {"lean", "cinematic", "maximal"}


def test_index_serves_html():
    res = client.get("/")
    assert res.status_code == 200
    assert "text/html" in res.headers["content-type"]


def test_plan_with_mock_backend_returns_full_project():
    res = client.post("/api/plan", json={"concept": "A lighthouse keeper meets a sea spirit."})
    assert res.status_code == 200
    session_id = res.json()["session_id"]

    project = _wait_for_plan(session_id)
    assert project["status"] == "complete"
    assert project["title"]
    assert project["scenes"]
    for scene in project["scenes"]:
        assert scene["shots"]

    render_plan = project["render_plan"]
    assert render_plan["intents"]
    assert render_plan["chains"]
    assert render_plan["order"]

    for intent in render_plan["intents"]:
        assert intent["description"]
        assert "negative" in intent
        assert intent["aspect_ratio"] == "16:9"


def test_plan_with_explicit_detail_level():
    res = client.post(
        "/api/plan", json={"concept": "A heist at a museum.", "backend": "mock", "detail": "lean"}
    )
    assert res.status_code == 200
    session_id = res.json()["session_id"]
    project = _wait_for_plan(session_id)
    assert project["render_plan"]["intents"]


def test_plan_rejects_unknown_backend():
    res = client.post("/api/plan", json={"concept": "x", "backend": "not-a-backend"})
    assert res.status_code == 400
    body = res.json()
    assert "error" in body
    assert "traceback" not in body["error"].lower()


def test_plan_rejects_unknown_detail():
    res = client.post("/api/plan", json={"concept": "x", "detail": "not-a-level"})
    assert res.status_code == 400
    assert "error" in res.json()


# ---------------------------------------------------------------------- #
# POST /api/plan starts a background job and returns immediately          #
# ---------------------------------------------------------------------- #


def test_plan_returns_before_generation_completes(gate):
    """The core claim of PR #29: the request returns the moment a job is
    started, not once Director-through-Prompter have all run."""
    gate.block_before("director")
    res = client.post("/api/plan", json={"concept": "A quiet heist."})
    assert res.status_code == 200
    body = res.json()
    assert set(body.keys()) == {"session_id", "status"}
    assert body["status"] in ("queued", "running")

    gate.wait_until_reached()  # proves the request really did return first
    gate.stop_blocking()
    _wait_for_plan(body["session_id"])


def test_session_exists_as_soon_as_plan_returns(gate):
    gate.block_before("director")
    res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = res.json()["session_id"]

    assert session_id in _sessions
    session = _sessions[session_id]
    assert session.plan_progress.status in ("queued", "running")

    gate.wait_until_reached()
    gate.stop_blocking()
    _wait_for_plan(session_id)


def test_plan_does_not_invoke_continuity(call_log):
    """Director/Writer/Designer/Cinematographer/Editor/Prompter run; the
    global ContinuityAgent does not — it is a separate request."""
    res = client.post("/api/plan", json={"concept": "A lighthouse keeper meets a sea spirit."})
    session_id = res.json()["session_id"]
    _wait_for_plan(session_id)
    assert "continuity" not in call_log


def test_completed_plan_includes_continuity_status_not_started():
    res = client.post("/api/plan", json={"concept": "A lighthouse keeper meets a sea spirit."})
    session_id = res.json()["session_id"]
    project = _wait_for_plan(session_id)
    assert project["continuity_status"] == "not_started"


def test_a_checkpoint_is_written_before_each_milestone_is_exposed(gate):
    """Requirement's ordering: generate result -> checkpoint -> expose.
    Caught here at the first scene's shots landing, by gating right after
    it (before the editor call) and checking the checkpoint on disk
    already agrees with what the progress endpoint is about to report."""
    gate.block_before("editor")
    res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = res.json()["session_id"]
    gate.wait_until_reached()

    session = _sessions[session_id]
    checkpoint = Path(session.session_dir) / "project_checkpoint.json"
    assert checkpoint.is_file()
    checkpointed = json.loads(checkpoint.read_text())
    assert len(checkpointed["scenes"]) == 1
    assert len(checkpointed["scenes"][0]["shots"]) == 2

    gate.stop_blocking()
    _wait_for_plan(session_id)


# ---------------------------------------------------------------------- #
# Incremental progress: stages, partial scenes, partial prompts           #
# ---------------------------------------------------------------------- #


def test_progress_stages_update_as_generation_proceeds(gate):
    gate.block_before("cinematographer")
    res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = res.json()["session_id"]
    gate.wait_until_reached()

    progress = client.get(f"/api/session/{session_id}/plan").json()
    assert progress["status"] == "running"
    assert progress["stage"] == "cinematography"
    assert progress["scene_count"] == 1
    assert progress["scenes_completed"] == 0

    gate.stop_blocking()
    final = _wait_for_plan(session_id)
    assert final["stage"] == "complete"


def test_stage_transitions_happen_in_a_fixed_order(gate):
    gate.block_before("director")
    res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = res.json()["session_id"]
    gate.wait_until_reached()

    def stage() -> str:
        return client.get(f"/api/session/{session_id}/plan").json()["stage"]

    seen = [stage()]
    for next_task in ("writer", "designer", "cinematographer", "editor", "prompter"):
        gate.block_before(next_task)
        assert gate.step(), f"never reached {next_task!r}"
        seen.append(stage())

    gate.stop_blocking()
    final = _wait_for_plan(session_id)
    seen.append(final["stage"])

    assert seen == [
        "director",
        "writer",
        "designer",
        "cinematography",
        "editor",
        "prompting",
        "complete",
    ]


def test_completed_scene_data_is_visible_before_the_whole_plan_completes(gate):
    gate.block_before("editor")
    res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = res.json()["session_id"]
    gate.wait_until_reached()

    progress = client.get(f"/api/session/{session_id}/plan").json()
    assert progress["status"] == "running"
    assert progress["scenes_completed"] == 1
    assert len(progress["scenes"]) == 1
    assert len(progress["scenes"][0]["shots"]) == 2
    # The editor call (which resolves order/chains — a precondition of
    # render_plan existing at all) hasn't run yet.
    assert progress["render_plan"] is None

    gate.stop_blocking()
    _wait_for_plan(session_id)


def test_completed_prompt_is_visible_before_remaining_prompts_finish(gate):
    gate.block_before("prompter")
    res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = res.json()["session_id"]
    gate.wait_until_reached()  # blocked before the 1st shot's prompter call

    got_second = gate.step()  # release the 1st call; block before the 2nd
    assert got_second, "expected a second prompter call for the mock's 2-shot scene"

    progress = client.get(f"/api/session/{session_id}/plan").json()
    assert progress["status"] == "running"
    assert progress["prompts_completed"] == 1
    assert len(progress["render_plan"]["intents"]) == 1
    assert progress["render_plan"]["intents"][0]["shot_id"] == "sc1-sh1"

    gate.stop_blocking()
    final = _wait_for_plan(session_id)
    assert final["prompts_completed"] == 2
    assert len(final["render_plan"]["intents"]) == 2


def test_partial_work_remains_accessible_after_a_later_generation_failure(failing_editor):
    """Completed creative work must never be lost with the request that
    was building the rest of it — here, the scene and its two shots
    survive an editor call that fails right after them."""
    res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = res.json()["session_id"]

    final = _wait_for_plan(session_id)
    assert final["status"] == "failed"
    assert "simulated editor outage" in final["error"]
    assert final["scenes_completed"] == 1
    assert len(final["scenes"]) == 1
    assert len(final["scenes"][0]["shots"]) == 2
    assert final["render_plan"] is None  # the editor never completed

    # Still reachable afterward too, not just in the one response that
    # reported the failure.
    again = client.get(f"/api/session/{session_id}/plan").json()
    assert again["status"] == "failed"
    assert len(again["scenes"]) == 1


def test_completed_job_returns_the_same_project_as_the_normal_pipeline():
    """The background portal path and the plain CLI path must agree: this
    isn't a second implementation of the pipeline, just the same one
    reporting progress as it goes."""
    from dataclasses import asdict

    from moviecrew.crew import MovieCrew

    concept = "A quiet heist."
    direct_project = MovieCrew(mock_module.MockLLMClient()).make(concept, run_continuity=False)
    expected = asdict(direct_project)

    res = client.post("/api/plan", json={"concept": concept})
    session_id = res.json()["session_id"]
    final = _wait_for_plan(session_id)

    for key in expected:
        assert final[key] == expected[key], key


# ---------------------------------------------------------------------- #
# Save Project: works before continuity has ever run                      #
# ---------------------------------------------------------------------- #


def test_save_project_succeeds_after_a_normal_plan():
    """Save must work before continuity runs at all — the continuity
    endpoint is never called in this test."""
    plan_res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = plan_res.json()["session_id"]
    project = _wait_for_plan(session_id)

    save_res = client.post(f"/api/session/{session_id}/save")
    assert save_res.status_code == 200

    saved_to = Path(save_res.json()["saved_to"])
    assert saved_to.is_file()
    saved = json.loads(saved_to.read_text())
    assert saved["title"] == project["title"]


def test_save_project_for_an_unknown_session_is_404():
    res = client.post("/api/session/does-not-exist/save")
    assert res.status_code == 404
    assert "error" in res.json()


# ---------------------------------------------------------------------- #
# POST /api/session/{id}/continuity: analysis of an already-built plan    #
# ---------------------------------------------------------------------- #


def test_continuity_does_not_start_until_plan_status_is_complete(gate):
    gate.block_before("prompter")
    res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = res.json()["session_id"]
    gate.wait_until_reached()

    refused = client.post(f"/api/session/{session_id}/continuity")
    assert refused.status_code == 409
    assert "continuity" not in gate.calls

    gate.stop_blocking()
    _wait_for_plan(session_id)

    accepted = client.post(f"/api/session/{session_id}/continuity")
    assert accepted.status_code == 200
    assert "continuity" in gate.calls


def test_continuity_endpoint_uses_the_existing_project_without_regenerating_it(call_log):
    plan_res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = plan_res.json()["session_id"]
    _wait_for_plan(session_id)
    assert "continuity" not in call_log
    calls_before_continuity = list(call_log)

    res = client.post(f"/api/session/{session_id}/continuity")
    assert res.status_code == 200
    assert call_log == calls_before_continuity + ["continuity"]


def test_continuity_success_updates_flags_and_status():
    plan_res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = plan_res.json()["session_id"]
    _wait_for_plan(session_id)

    res = client.post(f"/api/session/{session_id}/continuity")
    assert res.status_code == 200
    body = res.json()
    assert body["continuity_status"] == "complete"
    assert body["message"] is None
    assert any(
        f["target"] == "sc1-sh2" and "coat color" in f["message"] for f in body["flags"]
    )

    session = _sessions[session_id]
    assert session.continuity_status == "complete"
    assert any(f.target == "sc1-sh2" for f in session.project.render_plan.flags)


def test_continuity_failure_preserves_the_project_and_reports_failed(failing_continuity):
    """The requirement stated explicitly: continuity failure must never cost
    the plan, and must return a normal (not fatal) response."""
    plan_res = client.post("/api/plan", json={"concept": "A lighthouse keeper meets a sea spirit."})
    assert plan_res.status_code == 200
    session_id = plan_res.json()["session_id"]
    project = _wait_for_plan(session_id)

    res = client.post(f"/api/session/{session_id}/continuity")
    assert res.status_code == 200
    body = res.json()
    assert body["continuity_status"] == "failed"
    assert "simulated continuity outage" in body["message"]
    warnings = [f for f in body["flags"] if f["target"] == "project"]
    assert len(warnings) == 1
    assert warnings[0]["kind"] == "warning"

    session = _sessions[session_id]
    assert session.continuity_status == "failed"
    assert session.project.title == project["title"]
    assert session.project.scenes


def test_a_second_concurrent_continuity_run_is_refused(call_log):
    plan_res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = plan_res.json()["session_id"]
    _wait_for_plan(session_id)
    session = _sessions[session_id]
    session.continuity_status = "running"

    res = client.post(f"/api/session/{session_id}/continuity")
    assert res.status_code == 200
    body = res.json()
    assert body["continuity_status"] == "running"
    assert "already running" in body["message"]
    assert "continuity" not in call_log


def test_continuity_endpoint_for_an_unknown_session_is_404():
    res = client.post("/api/session/does-not-exist/continuity")
    assert res.status_code == 404
    assert "error" in res.json()


def test_project_is_persisted_after_continuity_completes():
    plan_res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = plan_res.json()["session_id"]
    _wait_for_plan(session_id)
    session = _sessions[session_id]

    client.post(f"/api/session/{session_id}/continuity")

    checkpoint = Path(session.session_dir) / "project_checkpoint.json"
    checkpointed = json.loads(checkpoint.read_text())
    assert any(f["target"] == "sc1-sh2" for f in checkpointed["render_plan"]["flags"])


def test_save_project_succeeds_even_though_continuity_failed(failing_continuity):
    """The requirement stated explicitly: Save must work when continuity is
    incomplete or failed, not only on the happy path."""
    plan_res = client.post("/api/plan", json={"concept": "A lighthouse keeper meets a sea spirit."})
    assert plan_res.status_code == 200
    session_id = plan_res.json()["session_id"]
    project = _wait_for_plan(session_id)

    continuity_res = client.post(f"/api/session/{session_id}/continuity")
    assert continuity_res.json()["continuity_status"] == "failed"

    save_res = client.post(f"/api/session/{session_id}/save")
    assert save_res.status_code == 200

    saved = json.loads(Path(save_res.json()["saved_to"]).read_text())
    assert saved["title"] == project["title"]
    assert any(f["target"] == "project" for f in saved["render_plan"]["flags"])
