"""Tests for the optional FastAPI portal (the PLAN path only).

Fully offline: uses fastapi.testclient.TestClient and the mock LLM backend,
no network and no real API key needed. Skips cleanly when the test client
isn't available (the `portal` extra is optional).

Guarded on TestClient itself rather than on `fastapi`, and catching
RuntimeError as well as ImportError: fastapi can import perfectly while
`fastapi.testclient` still fails, because starlette raises RuntimeError —
not ImportError — when its HTTP client dependency is missing. A plain
`importorskip("fastapi")` lets that through as a hard collection error.
"""

import json
from pathlib import Path

import pytest

try:
    from fastapi.testclient import TestClient
except (ImportError, RuntimeError) as exc:
    pytest.skip(f"fastapi TestClient unavailable: {exc}", allow_module_level=True)

import moviecrew.mock as mock_module  # noqa: E402
from moviecrew.portal.app import _sessions, app  # noqa: E402

client = TestClient(app)


@pytest.fixture
def call_log(monkeypatch):
    """Record every `task` passed to the mock LLM's complete_json, in the
    order it was invoked, without altering its behavior. Used to prove what
    did and did not get (re)generated by a given request.
    """
    calls: list[str] = []
    original = mock_module.MockLLMClient.complete_json

    def recording(self, *, task, system, user):
        calls.append(task)
        return original(self, task=task, system=system, user=user)

    monkeypatch.setattr(mock_module.MockLLMClient, "complete_json", recording)
    return calls


@pytest.fixture
def failing_continuity(monkeypatch):
    """Simulate the reported failure: continuity fails after everything
    else generated successfully. Patches the mock backend's own class
    method so the real code path (crew.make() / the continuity endpoint,
    through the mock LLM) is exercised, not a stand-in for it. Also records
    every task invoked, like call_log, so callers can assert on exactly
    what ran.
    """
    calls: list[str] = []
    original = mock_module.MockLLMClient.complete_json

    def sometimes_failing(self, *, task, system, user):
        calls.append(task)
        if task == "continuity":
            raise RuntimeError("simulated continuity outage")
        return original(self, task=task, system=system, user=user)

    monkeypatch.setattr(mock_module.MockLLMClient, "complete_json", sometimes_failing)
    return calls


def test_health_lists_backends_and_detail_levels():
    res = client.get("/api/health")
    assert res.status_code == 200
    data = res.json()
    assert data["ok"] is True
    assert "mock" in data["backends"]
    assert "anthropic" in data["backends"]
    assert set(data["detail_levels"]) == {"lean", "cinematic", "maximal"}


def test_index_serves_html():
    res = client.get("/")
    assert res.status_code == 200
    assert "text/html" in res.headers["content-type"]


def test_plan_with_mock_backend_returns_full_project():
    res = client.post("/api/plan", json={"concept": "A lighthouse keeper meets a sea spirit."})
    assert res.status_code == 200
    project = res.json()

    assert project["title"]
    assert project["scenes"]
    for scene in project["scenes"]:
        assert scene["shots"]

    render_plan = project["render_plan"]
    assert render_plan["intents"]
    assert render_plan["chains"]
    assert render_plan["order"]

    for intent in render_plan["intents"]:
        assert intent["description"]
        assert "negative" in intent
        assert intent["aspect_ratio"] == "16:9"


def test_plan_with_explicit_detail_level():
    res = client.post(
        "/api/plan", json={"concept": "A heist at a museum.", "backend": "mock", "detail": "lean"}
    )
    assert res.status_code == 200
    assert res.json()["render_plan"]["intents"]


def test_plan_rejects_unknown_backend():
    res = client.post("/api/plan", json={"concept": "x", "backend": "not-a-backend"})
    assert res.status_code == 400
    body = res.json()
    assert "error" in body
    assert "traceback" not in body["error"].lower()


def test_plan_rejects_unknown_detail():
    res = client.post("/api/plan", json={"concept": "x", "detail": "not-a-level"})
    assert res.status_code == 400
    assert "error" in res.json()


# ---------------------------------------------------------------------- #
# /api/plan returns immediately, without running continuity               #
# ---------------------------------------------------------------------- #


def test_plan_does_not_invoke_continuity(call_log):
    """Director/Writer/Designer/Cinematographer/Editor/Prompter run; the
    global ContinuityAgent does not — it is a separate request now."""
    res = client.post("/api/plan", json={"concept": "A lighthouse keeper meets a sea spirit."})
    assert res.status_code == 200
    assert "continuity" not in call_log


def test_plan_returns_full_scenes_shots_and_intents_immediately():
    res = client.post("/api/plan", json={"concept": "A lighthouse keeper meets a sea spirit."})
    assert res.status_code == 200

    project = res.json()
    assert project["title"]
    assert project["scenes"]
    for scene in project["scenes"]:
        assert scene["shots"]
    assert project["render_plan"]["intents"]
    assert project["session_id"]
    assert project["continuity_status"] == "not_started"


def test_session_exists_as_soon_as_plan_returns():
    res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = res.json()["session_id"]

    assert session_id in _sessions
    session = _sessions[session_id]
    assert session.continuity_status == "not_started"
    assert session.project.title == res.json()["title"]


def test_a_checkpoint_exists_on_disk_before_the_plan_response_is_even_returned():
    """The persistence half of the fix, exercised through the real endpoint:
    by the time /api/plan responds, a checkpoint of the plan (written before
    continuity ran) is already on disk in the session's own directory —
    independent of the in-memory Project the response itself carries. No
    continuity has run yet, so the checkpoint carries no project-level
    flag."""
    res = client.post("/api/plan", json={"concept": "A lighthouse keeper meets a sea spirit."})
    assert res.status_code == 200
    project = res.json()

    session = _sessions[project["session_id"]]
    checkpoint = Path(session.session_dir) / "project_checkpoint.json"
    assert checkpoint.is_file()
    checkpointed = json.loads(checkpoint.read_text())
    assert checkpointed["title"] == project["title"]
    assert not any(f["target"] == "project" for f in checkpointed["render_plan"]["flags"])


# ---------------------------------------------------------------------- #
# Save Project: works before continuity has ever run                      #
# ---------------------------------------------------------------------- #


def test_save_project_succeeds_after_a_normal_plan():
    """Save must work before continuity runs at all — the continuity
    endpoint is never called in this test."""
    plan_res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = plan_res.json()["session_id"]

    save_res = client.post(f"/api/session/{session_id}/save")
    assert save_res.status_code == 200

    saved_to = Path(save_res.json()["saved_to"])
    assert saved_to.is_file()
    saved = json.loads(saved_to.read_text())
    assert saved["title"] == plan_res.json()["title"]


def test_save_project_for_an_unknown_session_is_404():
    res = client.post("/api/session/does-not-exist/save")
    assert res.status_code == 404
    assert "error" in res.json()


# ---------------------------------------------------------------------- #
# POST /api/session/{id}/continuity: analysis of an already-built plan    #
# ---------------------------------------------------------------------- #


def test_continuity_endpoint_uses_the_existing_project_without_regenerating_it(call_log):
    plan_res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = plan_res.json()["session_id"]
    assert "continuity" not in call_log
    calls_before_continuity = list(call_log)

    res = client.post(f"/api/session/{session_id}/continuity")
    assert res.status_code == 200
    assert call_log == calls_before_continuity + ["continuity"]


def test_continuity_success_updates_flags_and_status():
    plan_res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = plan_res.json()["session_id"]

    res = client.post(f"/api/session/{session_id}/continuity")
    assert res.status_code == 200
    body = res.json()
    assert body["continuity_status"] == "complete"
    assert body["message"] is None
    assert any(
        f["target"] == "sc1-sh2" and "coat color" in f["message"] for f in body["flags"]
    )

    session = _sessions[session_id]
    assert session.continuity_status == "complete"
    assert any(f.target == "sc1-sh2" for f in session.project.render_plan.flags)


def test_continuity_failure_preserves_the_project_and_reports_failed(failing_continuity):
    """The requirement stated explicitly: continuity failure must never cost
    the plan, and must return a normal (not fatal) response."""
    plan_res = client.post("/api/plan", json={"concept": "A lighthouse keeper meets a sea spirit."})
    assert plan_res.status_code == 200
    session_id = plan_res.json()["session_id"]

    res = client.post(f"/api/session/{session_id}/continuity")
    assert res.status_code == 200
    body = res.json()
    assert body["continuity_status"] == "failed"
    assert "simulated continuity outage" in body["message"]
    warnings = [f for f in body["flags"] if f["target"] == "project"]
    assert len(warnings) == 1
    assert warnings[0]["kind"] == "warning"

    session = _sessions[session_id]
    assert session.continuity_status == "failed"
    assert session.project.title == plan_res.json()["title"]
    assert session.project.scenes


def test_a_second_concurrent_continuity_run_is_refused(call_log):
    plan_res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = plan_res.json()["session_id"]
    session = _sessions[session_id]
    session.continuity_status = "running"

    res = client.post(f"/api/session/{session_id}/continuity")
    assert res.status_code == 200
    body = res.json()
    assert body["continuity_status"] == "running"
    assert "already running" in body["message"]
    assert "continuity" not in call_log


def test_continuity_endpoint_for_an_unknown_session_is_404():
    res = client.post("/api/session/does-not-exist/continuity")
    assert res.status_code == 404
    assert "error" in res.json()


def test_project_is_persisted_after_continuity_completes():
    plan_res = client.post("/api/plan", json={"concept": "A quiet heist."})
    session_id = plan_res.json()["session_id"]
    session = _sessions[session_id]

    client.post(f"/api/session/{session_id}/continuity")

    checkpoint = Path(session.session_dir) / "project_checkpoint.json"
    checkpointed = json.loads(checkpoint.read_text())
    assert any(f["target"] == "sc1-sh2" for f in checkpointed["render_plan"]["flags"])


def test_save_project_succeeds_even_though_continuity_failed(failing_continuity):
    """The requirement stated explicitly: Save must work when continuity is
    incomplete or failed, not only on the happy path."""
    plan_res = client.post("/api/plan", json={"concept": "A lighthouse keeper meets a sea spirit."})
    assert plan_res.status_code == 200
    session_id = plan_res.json()["session_id"]

    continuity_res = client.post(f"/api/session/{session_id}/continuity")
    assert continuity_res.json()["continuity_status"] == "failed"

    save_res = client.post(f"/api/session/{session_id}/save")
    assert save_res.status_code == 200

    saved = json.loads(Path(save_res.json()["saved_to"]).read_text())
    assert saved["title"] == plan_res.json()["title"]
    assert any(f["target"] == "project" for f in saved["render_plan"]["flags"])
